### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by brianw921** [insidesherpa/bank-mergeCoTechTask1#48]
When I entered in the directions for python3 as followed I got the following error
```Traceback (most recent call last):
  File "client3.py", line 58, in <module>
    print ("Ratio %s" % (getRatio(prices['ABC'], prices['DEF'])))
NameError: name 'prices' is not defined ```

I then tried to search for the "prices" method/function and it's not there. 

Then I tried to access the price function, I get the following error.

```Traceback (most recent call last):
  File "client3.py", line 58, in <module>
    print ("Ratio %s" % (getRatio(price['ABC'], price['DEF'])))
TypeError: 'float' object is not subscriptable```


When I try to create a git patch file, it says that it is not a git repository

```
runner@9400d4b74689:~/JPM-MODULE1-PY3-REPL-2/jpm_module_1$ git add -A
fatal: not a git repository (or any parent up to mount point /home/runner)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).```

**Comment by harivansh0** [comment]
did you define dictionary  price ={}

**Comment by kirankuyate2157** [comment]
hey @brianw921, have you resolved this issue? if yes please tell me what the problem is.

**Comment by kirankuyate2157** [comment]
first, think you have to define **prieces={}**
then while iterating Quotes that time add then stocks with their price
**prices[stock] = price**
this is a Tab error I think
PS D:\professional work\JpMorgan\JPMC-tech-task-1-py3> python client3.py
  File "D:\professional work\JpMorgan\JPMC-tech-task-1-py3\client3.py", line 65
    for quote in quotes:
terror: inconsistent use of tabs and spaces in indentation

You can you single space instead of Tabs (tabs may be spaces diff but after  single spaces not going to be a problem 👍

Solution
`if __name__ == "__main__":

    # Query the price once every N seconds.
    for _ in range(N):
        quotes = json.loads(urllib.request.urlopen(
            QUERY.format(random.random())).read())
        """ ----------- Update to get the ratio --------------- """
        prices = {}
        for quote in quotes:
            stock, bid_price, ask_price, price = getDataPoint(quote)
            prices[stock] = price
            print("Quoted %s at (bid:%s, ask:%s, price:%s)" %
                  (stock, bid_price, ask_price, price))

        print("Ratio %s" % (getRatio(prices['ABC'], prices['DEF'])))
`
