### ISSUE TITLE
unable to create patch file even after following all instructions in module 1

### ISSUE THREAD

**Issue by riteshchhetri10** [insidesherpa/bank-mergeCoTechTask1#50]
i have written the code as instructed and even then after repeated attempts of opening a new REPL window too and following the procedure, the patch file doesn't appear in my folder.
i have attached the screenshot of my status.also there isn't any error message displayed.
![jpmc](https://user-images.githubusercontent.com/46395515/79683708-7677af00-8249-11ea-9534-a8fb1a2dcbff.png)
![Screenshot from 2020-04-19 14-24-52](https://user-images.githubusercontent.com/46395515/79683723-90b18d00-8249-11ea-8150-a091a0a2a590.png)

**Comment by riteshchhetri10** [comment]
if someone could help me out in creating this patch file it would really be a blessing

**Comment by surbhi1005** [comment]
Hi, I am facing a same kind of error but I am having a folder named 'git' created in my files sidebar instead of the patch file. Were you able to find any solution to your problem?
<img width="960" alt="jp" src="https://user-images.githubusercontent.com/41943765/79686583-20ae0180-825f-11ea-9c73-13b95d2a4618.PNG">

**Comment by riteshchhetri10** [comment]
yes i actually did. just log into repl using your github and just refresh it again and i got to see my two patches that i had created.
![patch](https://user-images.githubusercontent.com/46395515/79688706-9d47dc80-826d-11ea-9a16-eaea323e5216.png)
